### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by mengchaoheng** [carlonluca/docker-qt#2]
How to run [carlonluca/qt-dev](https://hub.docker.com/r/carlonluca/qt-dev)? when I use "docker run -it   carlonluca/qt-dev:latest", the output of terminal is 
```Consloe
➜  ~ docker run -it   carlonluca/qt-dev:latest 
/bin/bash: -c: option requires an argument
```

**Comment by carlonluca** [comment]
Hello,
what do you want to run? If you want a shell:

`docker run -it carlonluca/qt-dev:latest bash`
