### ISSUE TITLE
Document changes since 6.8.0

### ISSUE THREAD

**Issue by rikkuness** [carlonluca/docker-qt#7]
Hey, first of all thanks for these images, I had such a headache cross compiling Qt6 apps before I came across these images, it's made my life so much easier.

I've just been updating a project to build against 6.8.0 rather than 6.7.x and noticed a couple of things different and wasn't sure if it was worth documenting, some of it isn't possibly relevant.

First thing I noticed is that `appimage-builder` is now inside a venv, I'm assuming that to use it the same way I used before the practice should be to just activate the venv under `/venv` and then it's in the `PATH` as it was prior.

The second thing I noticed isn't actually probably relevant to this project as it's a change to `appimage-builder` itself, but seems like there's now an added `AppImage.comp` property to the appimage builder recipe that crashes the build if it's missing, again probably more documentation that's missing their end than here but felt worth noting as it broke my builds.

Appreciate 🙏🏻

**Comment by carlonluca** [comment]
Hello, you are correct about everything. I upgraded the base image from Jammy to Noble, and this is a consequence of that upgrade.

If you want to add a couple of notes to the Readme, you are welcome to open a PR, I'm sure it can be of help to others.

Thank you for pointing this out.
